### ISSUE TITLE
Colorize

### ISSUE THREAD

**Issue by 199862** [aqfaridi/pump_and_dump_bot#2]
Hi AQFARIDI
Can you help me?
Is Giving me this error

C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- colorize (LoadError)
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from bittrex_bot.rb:2:in `<main>'

**Comment by JackPoint** [comment]
Try `gem install colorize`

**Comment by sekapai** [comment]
thanks jack point..its work

**Comment by 199862** [comment]
thanks JackPoint

**Comment by Digitmind** [comment]
Hi, 

I encounter the following error:

```
ruby bittrex_bot.rb "DASH", "2"
Fetching Market Summary...
["https://bittrex.com/api/v1.1/public/getmarketsummary?market=BTC-DASH,", {"success"=>false, "message"=>"INVALID_MARKET", "result"=>nil}]
Failed/
bittrex_bot.rb:145:in `get_market_summary': undefined method `first' for nil:NilClass (NoMethodError)
	from bittrex_bot.rb:213:in `sell_bot'
	from bittrex_bot.rb:308:in `<main>'
```
The URL gives normal information in the browser.

Any idea? Thanks!
