### ISSUE TITLE
Purchase order not being completed

### ISSUE THREAD

**Issue by KBO2** [aqfaridi/pump_and_dump_bot#7]
Dear @aqfaridi,

Thank you so much for writting this great bot.
When i try to run the buy all option 5 bot everything works up till purchase. API key seems to be accepted but order is not being completed. Does anybody know why my order is not completing? I have enough balance in BTC and order is above minium orde amount on bitrex:

Purchasing coin...
[{:api_type=>"market", :action=>"buy", :market=>"BTC-BURST", :quantity=>310.55900621118013, :rate=>1.932e-06}]
Calling API...
["https://bittrex.com/api/v1.1/market/buylimit?market=BTC-BURST&quantity=310.55900621118013&rate=1.932e-06&apikey=<xxxxxxxxxxxxx>&nonce=xxxxxxxxxxxxx", {"success"=>false, "message"=>"There was a problem processing your request.  If this problem persists, please email support@bittrex.com with this error id - 18f25c09-f519-4352-94c7-94de5a60e1d5", "result"=>nil}]
Failed
Failed
[nil, "Units Bought : 0"]

**Comment by lacostenycoder** [comment]
looks like api key is not being passed as param, see url you posted`&apikey=&`
but also be careful not to post actually API keys here or anywhere where you don't want to publish them!  Check to make sure you have them set up correctly, should look something like
`API_KEY = "LKJSLDKFJ982989823"`

**Comment by KBO2** [comment]
@lacostenycoder , thank you so much I got it working by removing the brackets arround the API key :D  I just tested the program and posted 1 new issue, do you happen to have any experience with that error as well?
