### ISSUE TITLE
Error  Fetching Market Summary

### ISSUE THREAD

**Issue by ikhoa** [aqfaridi/pump_and_dump_bot#9]
Bot adds a "," at the end of the URL. Any idea on how i can remove it?
Thanks in advance 

ruby bittrex_bot.rb "SC", "3"
Fetching Market Summary...
["https://bittrex.com/api/v1.1/public/getmarketsummary?market=BTC-SC,", {"success"=>false, "message"=>"INVALID_MARKET", "result"=>nil}]
Failed
bittrex_bot.rb:145:in `get_market_summary': undefined method `first' for nil:NilClass (NoMethodError)
	from bittrex_bot.rb:249:in `buy_sell_bot'
	from bittrex_bot.rb:309:in `<main>'

**Comment by Digitmind** [comment]
Hi,
can you share your solution? Thanks!

**Comment by Digitmind** [comment]
Got it...
It's too simple :)
ruby bittrex_bot.rb "SC" "3" instead of ruby bittrex_bot.rb "SC", "3"
